on: push
name: Spectral Lint
jobs:
  spectralChecks:
    name: Spectral checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Spectral checks
        uses: ./
        with:
          file_path: test.oas.json
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          spectral_ruleset: 'spectral:oas'
